version: '{build}'

environment:
  access_token:
    secure: wxAvRgqg8ErfZm05ESB2zJxjwhny9wS0kRgK8TBDl2UeXnA06tqZPtNkwfRJc9SE

platform: x86
configuration: Release

build: 
    project: WindBot.sln
    parallel: true

after_build:
  - mv bin\Release WindBot
  - rm WindBot\WindBot.exe.config
  - mv BotWrapper\bin\Release\Bot.exe .
  - mv BotWrapper\bin\Release\bot.conf .
  - 7z a WindBot.7z WindBot Bot.exe bot.conf

test: off

artifacts:
  - path: WindBot.7z
    name: WindBot

deploy:
    description: 'Automatic build by Appveyor.'
    provider: GitHub
    auth_token: $(access_token)
    force_update: true
    on:
        appveyor_repo_tag: true
